### ISSUE TITLE
Org to Quarto

### ISSUE THREAD

**Issue by GTrunSec** [GTrunSec/data-science-threat-intelligence#16]
I got to know quarto from [JuliaCon's](https://jjallaire.github.io/quarto-juliacon-2022/#/section-3) PPT the other day. Since its theme was too beautiful for scientific analysis, I couldn't skip it. Due to your expertise in org-mode, I would like to know your @akirak idea if we can publish an org file to quarto.

**Comment by GTrunSec** [comment]
from https://github.com/GTrunSec/DeSci/pull/14. 
we have a real case that evaluates cells from org to quarto:
- https://luminous-creponne-5f9cc9.netlify.app/posts/julia-graph/
- https://luminous-creponne-5f9cc9.netlify.app/julia-graph

**Comment by GTrunSec** [comment]
or Should we focus more time on the organon instead of org-elisp?
- https://github.com/lucasvreis/organon/issues/5#issuecomment-1339761494

**Comment by akirak** [comment]
@GTrunSec Thank you for introducing me to Quatro. It looks quite interesting, and it makes sense for you to trying to adopt it. I might learn it in the future.

I currently have no experience in writing an Org export backend. We could learn from [ox-hugo](https://github.com/kaushalmodi/ox-hugo), which I know is the best piece of software in this field, but I cannot spend much time on it right now.

I didn't know of organon either. I only knew of org-hs written by the same author.

**Comment by GTrunSec** [comment]
@akirak  Thank you for your response. IMO, For a generic org-mode format converter, org-hs should be the best choice. In the role positioning of elisp and org, we might only require to care about the [results](https://github.com/GTrunSec/DeSci/pull/14/commits/e7b20d43dc9dddbf838fc6497e8917dd6e357d71#diff-ec63912ac63301dfcd324e8b6a7f727f9455b920a8962aafb37885a501557a6fR50) of org-bael evaluating through jupyter kernels.
