### ISSUE TITLE
Can't inspect the flake

### ISSUE THREAD

**Issue by akirak** [GTrunSec/data-science-threat-intelligence#18]
Hello, I want to explore Quatro and tried to explore this repository, so I first ran `nix flake show`, but I received an error:

> ❯ nix flake show github:GTrunSec/DeSci  
github:GTrunSec/DeSci/043f41899ea8d6c77b31581923f989958bbb6489
├───__functor: unknown
├───__std: unknown
├───aarch64-darwin: unknown
├───aarch64-linux: unknown
├───cicero: unknown
├───devShells
│   ├───aarch64-darwin
│   │   ├───default: development environment 'Data-Science-Threat-Intelligence'
│   │   ├───doc: development environment 'devshell'
│   │   ├───generator: development environment 'devshell'
│   │   ├───opencti: development environment 'devshell'
│   │   └───tullia: development environment 'devshell'
│   ├───aarch64-linux
│   │   ├───default: development environment 'Data-Science-Threat-Intelligence'
│   │   ├───doc: development environment 'devshell'
│   │   ├───generator: development environment 'devshell'
│   │   ├───opencti: development environment 'devshell'
│   │   └───tullia: development environment 'devshell'
│   ├───x86_64-darwin
│   │   ├───default: development environment 'Data-Science-Threat-Intelligence'
│   │   ├───doc: development environment 'devshell'
│   │   ├───generator: development environment 'devshell'
│   │   ├───opencti: development environment 'devshell'
│   │   └───tullia: development environment 'devshell'
│   └───x86_64-linux
│       ├───default: development environment 'Data-Science-Threat-Intelligence'
│       ├───doc: development environment 'devshell'
│       ├───generator: development environment 'devshell'
│       ├───opencti: development environment 'devshell'
│       └───tullia: development environment 'devshell'
├───packages
│   ├───aarch64-darwin
error: expected a derivation

There is something wrong with the structure of the flake (possibly due to `std`?).

I also ran `nix flake update` and got the following output:

> ❯ nix flake update                    
error: input 'dataflow2nix/std' follows a non-existent input 'dataflow2nix/cells-lab/std'
(use '--show-trace' to show detailed location information)

There seems to be no Nix package for Quatro. How am I supposed to install it on NixOS?

**Comment by GTrunSec** [comment]
Could you switch the branch to `layers` instead?

**Comment by GTrunSec** [comment]
I don't recommend you install quarto on nixos. That you only need a preconfigured shell enough.

- with native nix-comand
```
nix run .\#x86_64-linux.quarto.entrypoints.default ./nix/quarto/entrypoints/index.qmd 
```

- or std command
```
direnv allow or nix develop
std //quarto/entrypoints/default:run ./nix/quarto/entrypoints/index.qmd ```
```

**Comment by GTrunSec** [comment]
Also, I can export the libs to the flake interface so that you can import them in other flakes. Like `inputs.DeSci.lib.quarto.mkEnv {...}`

**Comment by akirak** [comment]
Thanks, now I can run quatro, but I still get the following error. Is there something I need to install to my user environment? 

> ❯ nix run .#x86_64-linux.quarto.entrypoints.default -- ./nix/quarto/entrypoints/index.qmd 
Error in library(dplyr) : there is no package called 'dplyr'
Calls: .main ... withVisible -> eval_with_user_handlers -> eval -> eval -> library
Execution halted

By the way, there is a typo in the package name. It should be `quatro`, not `quarto`.

**Comment by GTrunSec** [comment]
I did not add the dependence packages in the default command.  You can add [that](https://github.com/GTrunSec/DeSci/pull/14/commits/6a57155e0f918c6fc0ca3b5c062c9cd889161a44#diff-338578a1d8dea998a9aaf8db43eba77f568cbf4a597811ab68808b0e40029650R17) by yourself. Sorry my bad, the `https://quarto.org/` is corret.

**Comment by akirak** [comment]
> Sorry my bad, the https://quarto.org/ is corret.

I see, thanks.

I need some time to investigate this program.

**Comment by GTrunSec** [comment]
https://github.com/millejoh/emacs-ipython-notebook The experience of ein in org is unstable, and it‘s hard and challenging to replace jupyterlab. But you can based on the ein package and exec cells like Quatro with only a few lines of elisp.

You know, we have jupyter-kenrels. it powered all relevant languages.

```
jupyterlab 10.220.170.112 8888
```

```
jupyter --paths --json ```
