### ISSUE TITLE
Flexible package suiteProfile

### ISSUE THREAD

**Issue by GTrunSec** [GTrunSec/data-science-threat-intelligence#3]
@samrose https://github.com/fractal-dynamics/mach-nix-jupyterlab

Using mach-nix is ​​not a suitable choice. Jupyterwith and I use a mixture of poetry + nix ways to manage the python environment. This repo might give you some inspiration.

**Comment by samrose** [comment]
@GTrunSec yes thanks. I had a chance to meet Dan (the tweag lead of jupyterWith) at nixcon. I am now using it in other projects.

I do wonder what issues you see with mach-nix however?

**Comment by GTrunSec** [comment]
Poetry2nix has the advantage of giving you a faster nix-shell/develop, you don't need to eval the mach-nix every time especially when you enter the nix-shell env. So there is no big issue with mach-nix. Don't worry. I am already packaged mach-nix -env to a OCI image.
